include: 'https://gitlab.gnome.org/GNOME/citemplates/raw/master/flatpak/flatpak_ci_initiative.yml'

variables:
    BUNDLE: "four-in-a-row-dev.flatpak"

flatpak:
    image: 'registry.gitlab.gnome.org/gnome/gnome-runtime-images/gnome:master'
    variables:
        MANIFEST_PATH: "build-aux/org.gnome.Four-in-a-row.json"
        FLATPAK_MODULE: "four-in-a-row"
        RUNTIME_REPO: "https://sdk.gnome.org/gnome-nightly.flatpakrepo"
        APP_ID: "org.gnome.Four-in-a-row"
    extends: .flatpak

nightly:
    extends: '.publish_nightly'
    dependencies: ['flatpak']
    needs: ['flatpak']
