/* prefs.c generated by valac 0.42.2, the Vala compiler
 * generated from prefs.vala, do not modify */

/*public const int DEFAULT_THEME_ID = 0;*/
/*extern int n_themes;*/


#include <glib.h>
#include <glib-object.h>
#include <gio/gio.h>
#include <gtk/gtk.h>
#include <stdlib.h>
#include <string.h>
#include <config.h>
#include <prefs.h>
#include <gdk/gdk.h>
#include <theme.h>
#include <glib/gi18n-lib.h>
#include <main.h>
#include <float.h>
#include <math.h>

#define _g_object_unref0(var) ((var == NULL) ? NULL : (var = (g_object_unref (var), NULL)))
#define _g_free0(var) (var = (g_free (var), NULL))


extern GSettings* settings;
extern GtkDialog* prefsbox;
GtkDialog* prefsbox = NULL;
extern GtkComboBox* combobox;
GtkComboBox* combobox = NULL;
extern GtkComboBoxText* combobox_theme;
GtkComboBoxText* combobox_theme = NULL;
extern GtkCheckButton* checkbutton_sound;
GtkCheckButton* checkbutton_sound = NULL;
extern Prefs p;
Prefs p = {0};
extern PlayerID who_starts;
extern GtkWindow* window;

#define GETTEXT_PACKAGE_CONTENT GETTEXT_PACKAGE
#define DEFAULT_KEY_LEFT GDK_KEY_Left
#define DEFAULT_KEY_RIGHT GDK_KEY_Right
#define DEFAULT_KEY_DROP GDK_KEY_Down
#define DEFAULT_THEME_ID 0
gint sane_theme_id (gint val);
gint sane_player_level (gint val);
void on_select_theme (GtkComboBox* combo);
void on_toggle_sound (GtkToggleButton* t);
void prefs_init (void);
void settings_changed_cb (const gchar* key);
static void _settings_changed_cb_g_settings_changed (GSettings* _sender,
                                              const gchar* key,
                                              gpointer self);
gboolean gfx_change_theme (void);
void on_select_opponent (GtkComboBox* w);
void scorebox_reset (void);
void prefsbox_open (void);
static void _on_select_opponent_gtk_combo_box_changed (GtkComboBox* _sender,
                                                gpointer self);
gchar* theme_get_title (gint id);
static void _on_select_theme_gtk_combo_box_changed (GtkComboBox* _sender,
                                             gpointer self);
static void _on_toggle_sound_gtk_toggle_button_toggled (GtkToggleButton* _sender,
                                                 gpointer self);

extern const Theme theme[5];

gint
sane_theme_id (gint val)
{
	gint result = 0;
	gboolean _tmp0_ = FALSE;
	if (val < 0) {
		_tmp0_ = TRUE;
	} else {
		_tmp0_ = val >= G_N_ELEMENTS (theme);
	}
	if (_tmp0_) {
		result = DEFAULT_THEME_ID;
		return result;
	}
	result = val;
	return result;
}


gint
sane_player_level (gint val)
{
	gint result = 0;
	if (val < ((gint) LEVEL_HUMAN)) {
		result = (gint) LEVEL_HUMAN;
		return result;
	}
	if (val > ((gint) LEVEL_STRONG)) {
		result = (gint) LEVEL_STRONG;
		return result;
	}
	result = val;
	return result;
}


void
on_select_theme (GtkComboBox* combo)
{
	gint id = 0;
	GSettings* _tmp0_;
	g_return_if_fail (combo != NULL);
	id = gtk_combo_box_get_active (combo);
	_tmp0_ = settings;
	g_settings_set_int (_tmp0_, "theme-id", id);
}


void
on_toggle_sound (GtkToggleButton* t)
{
	GSettings* _tmp0_;
	g_return_if_fail (t != NULL);
	p.do_sound = gtk_toggle_button_get_active (t);
	_tmp0_ = settings;
	g_settings_set_boolean (_tmp0_, "sound", gtk_toggle_button_get_active (t));
}


static void
_settings_changed_cb_g_settings_changed (GSettings* _sender,
                                         const gchar* key,
                                         gpointer self)
{
	settings_changed_cb (key);
}


void
prefs_init (void)
{
	GSettings* _tmp0_;
	LevelID _tmp1_;
	GSettings* _tmp2_;
	LevelID _tmp3_;
	GSettings* _tmp4_;
	gint _tmp5_;
	GSettings* _tmp6_;
	gint _tmp7_;
	GSettings* _tmp8_;
	gint _tmp9_;
	GSettings* _tmp10_;
	GSettings* _tmp11_;
	Prefs _tmp12_;
	LevelID _tmp13_;
	LevelID _tmp14_;
	Prefs _tmp15_;
	LevelID _tmp16_;
	LevelID _tmp17_;
	Prefs _tmp18_;
	gint _tmp19_;
	_tmp0_ = settings;
	p.do_sound = g_settings_get_boolean (_tmp0_, "sound");
	p.level[PLAYER1] = LEVEL_HUMAN;
	_tmp1_ = p.level[PLAYER1];
	_tmp2_ = settings;
	p.level[PLAYER2] = (LevelID) g_settings_get_int (_tmp2_, "opponent");
	_tmp3_ = p.level[PLAYER2];
	_tmp4_ = settings;
	p.keypress[MOVE_LEFT] = g_settings_get_int (_tmp4_, "key-left");
	_tmp5_ = p.keypress[MOVE_LEFT];
	_tmp6_ = settings;
	p.keypress[MOVE_RIGHT] = g_settings_get_int (_tmp6_, "key-right");
	_tmp7_ = p.keypress[MOVE_RIGHT];
	_tmp8_ = settings;
	p.keypress[MOVE_DROP] = g_settings_get_int (_tmp8_, "key-drop");
	_tmp9_ = p.keypress[MOVE_DROP];
	_tmp10_ = settings;
	p.theme_id = g_settings_get_int (_tmp10_, "theme-id");
	_tmp11_ = settings;
	g_signal_connect (_tmp11_, "changed", (GCallback) _settings_changed_cb_g_settings_changed, NULL);
	_tmp12_ = p;
	_tmp13_ = _tmp12_.level[PLAYER1];
	p.level[PLAYER1] = (LevelID) sane_player_level ((gint) _tmp13_);
	_tmp14_ = p.level[PLAYER1];
	_tmp15_ = p;
	_tmp16_ = _tmp15_.level[PLAYER2];
	p.level[PLAYER2] = (LevelID) sane_player_level ((gint) _tmp16_);
	_tmp17_ = p.level[PLAYER2];
	_tmp18_ = p;
	_tmp19_ = _tmp18_.theme_id;
	p.theme_id = sane_theme_id (_tmp19_);
}


void
settings_changed_cb (const gchar* key)
{
	g_return_if_fail (key != NULL);
	if (g_strcmp0 (key, "sound") == 0) {
		GSettings* _tmp0_;
		GtkCheckButton* _tmp1_;
		Prefs _tmp2_;
		gboolean _tmp3_;
		_tmp0_ = settings;
		p.do_sound = g_settings_get_boolean (_tmp0_, "sound");
		_tmp1_ = checkbutton_sound;
		_tmp2_ = p;
		_tmp3_ = _tmp2_.do_sound;
		gtk_toggle_button_set_active (G_TYPE_CHECK_INSTANCE_CAST (_tmp1_, gtk_toggle_button_get_type (), GtkToggleButton), _tmp3_);
	} else {
		if (g_strcmp0 (key, "key-left") == 0) {
			GSettings* _tmp4_;
			gint _tmp5_;
			_tmp4_ = settings;
			p.keypress[MOVE_LEFT] = g_settings_get_int (_tmp4_, "key-left");
			_tmp5_ = p.keypress[MOVE_LEFT];
		} else {
			if (g_strcmp0 (key, "key-right") == 0) {
				GSettings* _tmp6_;
				gint _tmp7_;
				_tmp6_ = settings;
				p.keypress[MOVE_RIGHT] = g_settings_get_int (_tmp6_, "key-right");
				_tmp7_ = p.keypress[MOVE_RIGHT];
			} else {
				if (g_strcmp0 (key, "key-drop") == 0) {
					GSettings* _tmp8_;
					gint _tmp9_;
					_tmp8_ = settings;
					p.keypress[MOVE_DROP] = g_settings_get_int (_tmp8_, "key-drop");
					_tmp9_ = p.keypress[MOVE_DROP];
				} else {
					if (g_strcmp0 (key, "theme-id") == 0) {
						gint val = 0;
						GSettings* _tmp10_;
						gint _tmp11_;
						Prefs _tmp12_;
						gint _tmp13_;
						_tmp10_ = settings;
						val = sane_theme_id (g_settings_get_int (_tmp10_, "theme-id"));
						_tmp11_ = val;
						_tmp12_ = p;
						_tmp13_ = _tmp12_.theme_id;
						if (_tmp11_ != _tmp13_) {
							gint _tmp14_;
							GtkDialog* _tmp15_;
							GtkComboBoxText* _tmp16_;
							Prefs _tmp17_;
							gint _tmp18_;
							_tmp14_ = val;
							p.theme_id = _tmp14_;
							if (!gfx_change_theme ()) {
								return;
							}
							_tmp15_ = prefsbox;
							if (_tmp15_ == NULL) {
								return;
							}
							_tmp16_ = combobox_theme;
							_tmp17_ = p;
							_tmp18_ = _tmp17_.theme_id;
							gtk_combo_box_set_active (G_TYPE_CHECK_INSTANCE_CAST (_tmp16_, gtk_combo_box_get_type (), GtkComboBox), _tmp18_);
						}
					}
				}
			}
		}
	}
}


void
on_select_opponent (GtkComboBox* w)
{
	GtkTreeIter iter = {0};
	gint value = 0;
	GtkTreeIter _tmp0_ = {0};
	GtkTreeModel* _tmp1_;
	GtkTreeIter _tmp2_;
	LevelID _tmp3_;
	GSettings* _tmp4_;
	g_return_if_fail (w != NULL);
	gtk_combo_box_get_active_iter (w, &_tmp0_);
	iter = _tmp0_;
	_tmp1_ = gtk_combo_box_get_model (w);
	_tmp2_ = iter;
	gtk_tree_model_get (_tmp1_, &_tmp2_, 1, &value, -1);
	p.level[PLAYER2] = (LevelID) value;
	_tmp3_ = p.level[PLAYER2];
	_tmp4_ = settings;
	g_settings_set_int (_tmp4_, "opponent", value);
	scorebox_reset ();
	who_starts = PLAYER2;
	game_reset ();
}


static void
_on_select_opponent_gtk_combo_box_changed (GtkComboBox* _sender,
                                           gpointer self)
{
	on_select_opponent (_sender);
}


static void
_on_select_theme_gtk_combo_box_changed (GtkComboBox* _sender,
                                        gpointer self)
{
	on_select_theme (_sender);
}


static void
_on_toggle_sound_gtk_toggle_button_toggled (GtkToggleButton* _sender,
                                            gpointer self)
{
	on_toggle_sound (_sender);
}


void
prefsbox_open (void)
{
	GtkNotebook* notebook = NULL;
	GtkGrid* grid = NULL;
	GtkLabel* label = NULL;
	GtkCellRendererText* renderer = NULL;
	GtkListStore* model = NULL;
	GtkTreeIter iter = {0};
	GtkDialog* _tmp0_;
	GtkWindow* _tmp2_;
	GtkDialog* _tmp3_;
	GtkDialog* _tmp4_;
	GtkDialog* _tmp5_;
	GtkBox* _tmp6_;
	GtkNotebook* _tmp7_;
	GtkNotebook* _tmp8_;
	GtkDialog* _tmp9_;
	GtkBox* _tmp10_;
	GtkNotebook* _tmp11_;
	GtkGrid* _tmp12_;
	GtkGrid* _tmp13_;
	GtkGrid* _tmp14_;
	GtkGrid* _tmp15_;
	GtkLabel* _tmp16_;
	GtkNotebook* _tmp17_;
	GtkGrid* _tmp18_;
	GtkLabel* _tmp19_;
	GtkLabel* _tmp20_;
	GtkLabel* _tmp21_;
	GtkGrid* _tmp22_;
	GtkLabel* _tmp23_;
	GtkComboBox* _tmp24_;
	GtkCellRendererText* _tmp25_;
	GtkComboBox* _tmp26_;
	GtkCellRendererText* _tmp27_;
	GtkComboBox* _tmp28_;
	GtkCellRendererText* _tmp29_;
	GtkListStore* _tmp30_;
	GtkComboBox* _tmp31_;
	GtkListStore* _tmp32_;
	GtkListStore* _tmp33_;
	GtkTreeIter _tmp34_ = {0};
	GtkListStore* _tmp35_;
	GtkTreeIter _tmp36_;
	Prefs _tmp37_;
	LevelID _tmp38_;
	GtkListStore* _tmp41_;
	GtkTreeIter _tmp42_ = {0};
	GtkListStore* _tmp43_;
	GtkTreeIter _tmp44_;
	Prefs _tmp45_;
	LevelID _tmp46_;
	GtkListStore* _tmp49_;
	GtkTreeIter _tmp50_ = {0};
	GtkListStore* _tmp51_;
	GtkTreeIter _tmp52_;
	Prefs _tmp53_;
	LevelID _tmp54_;
	GtkListStore* _tmp57_;
	GtkTreeIter _tmp58_ = {0};
	GtkListStore* _tmp59_;
	GtkTreeIter _tmp60_;
	Prefs _tmp61_;
	LevelID _tmp62_;
	GtkComboBox* _tmp65_;
	GtkGrid* _tmp66_;
	GtkComboBox* _tmp67_;
	GtkLabel* _tmp68_;
	GtkLabel* _tmp69_;
	GtkLabel* _tmp70_;
	GtkGrid* _tmp71_;
	GtkLabel* _tmp72_;
	GtkComboBoxText* _tmp73_;
	GtkLabel* _tmp81_;
	GtkComboBoxText* _tmp82_;
	GtkGrid* _tmp83_;
	GtkComboBoxText* _tmp84_;
	GtkCheckButton* _tmp85_;
	GtkGrid* _tmp86_;
	GtkCheckButton* _tmp87_;
	GtkLabel* _tmp88_;
	GtkComboBoxText* _tmp89_;
	Prefs _tmp90_;
	gint _tmp91_;
	GtkCheckButton* _tmp92_;
	Prefs _tmp93_;
	gboolean _tmp94_;
	GtkComboBoxText* _tmp95_;
	GtkCheckButton* _tmp96_;
	GtkDialog* _tmp97_;
	_tmp0_ = prefsbox;
	if (_tmp0_ != NULL) {
		GtkDialog* _tmp1_;
		_tmp1_ = prefsbox;
		gtk_window_present (G_TYPE_CHECK_INSTANCE_CAST (_tmp1_, gtk_window_get_type (), GtkWindow));
		_g_object_unref0 (model);
		_g_object_unref0 (renderer);
		_g_object_unref0 (label);
		_g_object_unref0 (grid);
		_g_object_unref0 (notebook);
		return;
	}
	_tmp2_ = window;
	_tmp3_ = (GtkDialog*) gtk_dialog_new_with_buttons (_ ("Preferences"), _tmp2_, GTK_DIALOG_DESTROY_WITH_PARENT, NULL);
	g_object_ref_sink (_tmp3_);
	_g_object_unref0 (prefsbox);
	prefsbox = _tmp3_;
	_tmp4_ = prefsbox;
	gtk_container_set_border_width ((GtkContainer*) _tmp4_, (guint) 5);
	_tmp5_ = prefsbox;
	_tmp6_ = gtk_dialog_get_content_area (_tmp5_);
	gtk_box_set_spacing (_tmp6_, 2);
	_tmp7_ = (GtkNotebook*) gtk_notebook_new ();
	g_object_ref_sink (_tmp7_);
	_g_object_unref0 (notebook);
	notebook = _tmp7_;
	_tmp8_ = notebook;
	gtk_container_set_border_width ((GtkContainer*) _tmp8_, (guint) 5);
	_tmp9_ = prefsbox;
	_tmp10_ = gtk_dialog_get_content_area (_tmp9_);
	_tmp11_ = notebook;
	gtk_box_pack_start (_tmp10_, (GtkWidget*) _tmp11_, TRUE, TRUE, (guint) 0);
	_tmp12_ = (GtkGrid*) gtk_grid_new ();
	g_object_ref_sink (_tmp12_);
	_g_object_unref0 (grid);
	grid = _tmp12_;
	_tmp13_ = grid;
	gtk_grid_set_row_spacing (_tmp13_, (guint) 6);
	_tmp14_ = grid;
	gtk_grid_set_column_spacing (_tmp14_, (guint) 12);
	_tmp15_ = grid;
	gtk_container_set_border_width ((GtkContainer*) _tmp15_, (guint) 12);
	_tmp16_ = (GtkLabel*) gtk_label_new (_ ("Game"));
	g_object_ref_sink (_tmp16_);
	_g_object_unref0 (label);
	label = _tmp16_;
	_tmp17_ = notebook;
	_tmp18_ = grid;
	_tmp19_ = label;
	gtk_notebook_append_page (_tmp17_, (GtkWidget*) _tmp18_, (GtkWidget*) _tmp19_);
	_tmp20_ = (GtkLabel*) gtk_label_new (_ ("Opponent:"));
	g_object_ref_sink (_tmp20_);
	_g_object_unref0 (label);
	label = _tmp20_;
	_tmp21_ = label;
	gtk_widget_set_hexpand ((GtkWidget*) _tmp21_, TRUE);
	_tmp22_ = grid;
	_tmp23_ = label;
	gtk_grid_attach (_tmp22_, (GtkWidget*) _tmp23_, 0, 0, 1, 1);
	_tmp24_ = (GtkComboBox*) gtk_combo_box_new ();
	g_object_ref_sink (_tmp24_);
	_g_object_unref0 (combobox);
	combobox = _tmp24_;
	_tmp25_ = (GtkCellRendererText*) gtk_cell_renderer_text_new ();
	g_object_ref_sink (_tmp25_);
	_g_object_unref0 (renderer);
	renderer = _tmp25_;
	_tmp26_ = combobox;
	_tmp27_ = renderer;
	gtk_cell_layout_pack_start ((GtkCellLayout*) _tmp26_, (GtkCellRenderer*) _tmp27_, TRUE);
	_tmp28_ = combobox;
	_tmp29_ = renderer;
	gtk_cell_layout_add_attribute ((GtkCellLayout*) _tmp28_, (GtkCellRenderer*) _tmp29_, "text", 0);
	_tmp30_ = gtk_list_store_new (2, G_TYPE_STRING, G_TYPE_INT, -1);
	_g_object_unref0 (model);
	model = _tmp30_;
	_tmp31_ = combobox;
	_tmp32_ = model;
	gtk_combo_box_set_model (_tmp31_, (GtkTreeModel*) _tmp32_);
	_tmp33_ = model;
	gtk_list_store_append (_tmp33_, &_tmp34_);
	iter = _tmp34_;
	_tmp35_ = model;
	_tmp36_ = iter;
	gtk_list_store_set (_tmp35_, &_tmp36_, 0, _ ("Human"), 1, LEVEL_HUMAN, -1);
	_tmp37_ = p;
	_tmp38_ = _tmp37_.level[PLAYER2];
	if (_tmp38_ == LEVEL_HUMAN) {
		GtkComboBox* _tmp39_;
		GtkTreeIter _tmp40_;
		_tmp39_ = combobox;
		_tmp40_ = iter;
		gtk_combo_box_set_active_iter (_tmp39_, &_tmp40_);
	}
	_tmp41_ = model;
	gtk_list_store_append (_tmp41_, &_tmp42_);
	iter = _tmp42_;
	_tmp43_ = model;
	_tmp44_ = iter;
	gtk_list_store_set (_tmp43_, &_tmp44_, 0, _ ("Level one"), 1, LEVEL_WEAK, -1);
	_tmp45_ = p;
	_tmp46_ = _tmp45_.level[PLAYER2];
	if (_tmp46_ == LEVEL_WEAK) {
		GtkComboBox* _tmp47_;
		GtkTreeIter _tmp48_;
		_tmp47_ = combobox;
		_tmp48_ = iter;
		gtk_combo_box_set_active_iter (_tmp47_, &_tmp48_);
	}
	_tmp49_ = model;
	gtk_list_store_append (_tmp49_, &_tmp50_);
	iter = _tmp50_;
	_tmp51_ = model;
	_tmp52_ = iter;
	gtk_list_store_set (_tmp51_, &_tmp52_, 0, _ ("Level two"), 1, LEVEL_MEDIUM, -1);
	_tmp53_ = p;
	_tmp54_ = _tmp53_.level[PLAYER2];
	if (_tmp54_ == LEVEL_MEDIUM) {
		GtkComboBox* _tmp55_;
		GtkTreeIter _tmp56_;
		_tmp55_ = combobox;
		_tmp56_ = iter;
		gtk_combo_box_set_active_iter (_tmp55_, &_tmp56_);
	}
	_tmp57_ = model;
	gtk_list_store_append (_tmp57_, &_tmp58_);
	iter = _tmp58_;
	_tmp59_ = model;
	_tmp60_ = iter;
	gtk_list_store_set (_tmp59_, &_tmp60_, 0, _ ("Level thre"), 1, LEVEL_STRONG, -1);
	_tmp61_ = p;
	_tmp62_ = _tmp61_.level[PLAYER2];
	if (_tmp62_ == LEVEL_STRONG) {
		GtkComboBox* _tmp63_;
		GtkTreeIter _tmp64_;
		_tmp63_ = combobox;
		_tmp64_ = iter;
		gtk_combo_box_set_active_iter (_tmp63_, &_tmp64_);
	}
	_tmp65_ = combobox;
	g_signal_connect (_tmp65_, "changed", (GCallback) _on_select_opponent_gtk_combo_box_changed, NULL);
	_tmp66_ = grid;
	_tmp67_ = combobox;
	gtk_grid_attach (_tmp66_, (GtkWidget*) _tmp67_, 1, 0, 1, 1);
	_tmp68_ = (GtkLabel*) gtk_label_new_with_mnemonic (_ ("_Theme:"));
	g_object_ref_sink (_tmp68_);
	_g_object_unref0 (label);
	label = _tmp68_;
	_tmp69_ = label;
	gtk_label_set_xalign (_tmp69_, (gfloat) 0.0);
	_tmp70_ = label;
	gtk_label_set_yalign (_tmp70_, (gfloat) 0.5);
	_tmp71_ = grid;
	_tmp72_ = label;
	gtk_grid_attach (_tmp71_, (GtkWidget*) _tmp72_, 0, 1, 1, 1);
	_tmp73_ = (GtkComboBoxText*) gtk_combo_box_text_new ();
	g_object_ref_sink (_tmp73_);
	_g_object_unref0 (combobox_theme);
	combobox_theme = _tmp73_;
	{
		gint i = 0;
		i = 0;
		{
			gboolean _tmp74_ = FALSE;
			_tmp74_ = TRUE;
			while (TRUE) {
				gint _tmp76_;
				GtkComboBoxText* _tmp77_;
				gint _tmp78_;
				gchar* _tmp79_;
				gchar* _tmp80_;
				if (!_tmp74_) {
					gint _tmp75_;
					_tmp75_ = i;
					i = _tmp75_ + 1;
				}
				_tmp74_ = FALSE;
				_tmp76_ = i;
				if (!(_tmp76_ < G_N_ELEMENTS (theme))) {
					break;
				}
				_tmp77_ = combobox_theme;
				_tmp78_ = i;
				_tmp79_ = theme_get_title (_tmp78_);
				_tmp80_ = _tmp79_;
				gtk_combo_box_text_append_text (_tmp77_, _ (_tmp80_));
				_g_free0 (_tmp80_);
			}
		}
	}
	_tmp81_ = label;
	_tmp82_ = combobox_theme;
	gtk_label_set_mnemonic_widget (_tmp81_, (GtkWidget*) _tmp82_);
	_tmp83_ = grid;
	_tmp84_ = combobox_theme;
	gtk_grid_attach (_tmp83_, (GtkWidget*) _tmp84_, 1, 1, 1, 1);
	_tmp85_ = (GtkCheckButton*) gtk_check_button_new_with_mnemonic (_ ("E_nable sounds"));
	g_object_ref_sink (_tmp85_);
	_g_object_unref0 (checkbutton_sound);
	checkbutton_sound = _tmp85_;
	_tmp86_ = grid;
	_tmp87_ = checkbutton_sound;
	gtk_grid_attach (_tmp86_, (GtkWidget*) _tmp87_, 0, 2, 2, 1);
	_tmp88_ = (GtkLabel*) gtk_label_new_with_mnemonic (_ ("Keyboard Controls"));
	g_object_ref_sink (_tmp88_);
	_g_object_unref0 (label);
	label = _tmp88_;
	_tmp89_ = combobox_theme;
	_tmp90_ = p;
	_tmp91_ = _tmp90_.theme_id;
	gtk_combo_box_set_active ((GtkComboBox*) _tmp89_, _tmp91_);
	_tmp92_ = checkbutton_sound;
	_tmp93_ = p;
	_tmp94_ = _tmp93_.do_sound;
	gtk_toggle_button_set_active ((GtkToggleButton*) _tmp92_, _tmp94_);
	_tmp95_ = combobox_theme;
	g_signal_connect ((GtkComboBox*) _tmp95_, "changed", (GCallback) _on_select_theme_gtk_combo_box_changed, NULL);
	_tmp96_ = checkbutton_sound;
	g_signal_connect ((GtkToggleButton*) _tmp96_, "toggled", (GCallback) _on_toggle_sound_gtk_toggle_button_toggled, NULL);
	_tmp97_ = prefsbox;
	gtk_widget_show_all ((GtkWidget*) _tmp97_);
	_g_object_unref0 (model);
	_g_object_unref0 (renderer);
	_g_object_unref0 (label);
	_g_object_unref0 (grid);
	_g_object_unref0 (notebook);
}



